### PR TITLE
Add warning if packages.config is used

### LINKED ISSUE #45: Update readme and add warning for projects using packages.config
### Description

Source generators might not be loaded correctly in legacy-style .csproj projects on NETFX (see #39, #43). The readme should include a warning explaining this, with a link to the [SDK-style .csproj project docs](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/overview) to help users understand how to fix things.

### PR DESCRIPTION
**Pull request by Sergio0694**
### Description

This PR adds a warning if packages.config is used in consuming projects.

### CODE REVIEW

**Comment by Sergio0694** [comment]
Hey @cremor, I'm having trouble setting up a local packages.config project to validate this. If you have time, could you try getting the package from the build artifacts here (you can find it [here](https://github.com/Sergio0694/PolySharp/actions/runs/3929965828)) and see if you correctly get the warning? Thank you! 🙂

**Comment by cremor** [comment]
Not getting any warning in my sample project: [ConsoleApp1.zip](https://github.com/Sergio0694/PolySharp/files/10426989/ConsoleApp1.zip)

But I think I added it correctly because after using the VS feature to convert packages.config to `<PackageReference>` the files are generated correctly.

**Comment by DreadLordMikey** [comment]
Is the implication here that consuming applications would be encouraged to migrate away from the use of a `packages.config` file and towards the use of `<PackageReference/>`s in their `.csproj` project files?

**Comment by Sergio0694** [comment]
Yes. Source generators just don't seem to work at all with packages.config, so I don't think they'd have much of a choice 😅
Other than, of course, not using PolySharp at all. But also, packages.config is just terrible, so not a great loss ahah

**Comment by DreadLordMikey** [comment]
Alrighty then! I'll annotate that on my unit test repo for future reference. :)

**Comment by Sergio0694** [comment]
Hey @cremor, I've updated the .targets file with new logic to check for packages.config, it should work correctly now 😄

**Pull request merged**
