### PR TITLE
Add polyfills for .NET 9 attributes.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
### API breakdown (for new features)

Polyfills for the following attributes were added:

* `[OverloadResolutionPriority]`
* `[ParamsCollection]`

Polyfills for the following runtime-supported attributes were added:

* `[DisableUserUnhandledExceptions]`
* `[FeatureGuard]`
* `[FeatureSwitchDefinition]`
* `[WasmImportLinkage]`

Some of the runtime-supported attributes like the first and the last, might be considered too niche to polyfill. I'd be fine with removing them from the PR.

### Additional context (optional)

The list of attributes was populated by searching for the string `Attribute {` in files matching `release-notes/9.0/**/Microsoft.NETCore.App` in the `dotnet/core` repository, and excluding the attributes in `System.Text.Json`.

Test coverage for the language support polyfills was added.

### CODE REVIEW

**Comment by teo-tsirpanis** [comment]
@Sergio0694 could you take a look now that .NET 9 released? Thanks.

**Comment by Sergio0694** [comment]
Yup, on my todo list! Waiting for GitHub Actions to update the VM images to include the .NET 9 SDK 🙂

**Comment by bgrainger** [comment]
> Waiting for GitHub Actions to update the VM images to include the .NET 9 SDK

If you add `setup-dotnet` to your GHA workflow, it will install the SDK version specified by `global.json`: https://github.com/Sergio0694/PolySharp/pull/113

**Review by Sergio0694 — COMMENTED** [review]
LGTM, thank you! 🙂

**Pull request merged**
